plugins {
    id 'com.android.application'
}

android {
    namespace 'com.thumbtype.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.sadam.thumbtype.mobile"
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName "1.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.activity:activity:1.10.0'
}
