package com.sadam.thumbtype.mobile

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale
import kotlin.math.roundToInt

class AppRepository(context:Context){
 private val prefs=context.getSharedPreferences("thumbtype_elite_v3",Context.MODE_PRIVATE);private val dateFormat=SimpleDateFormat("yyyy-MM-dd",Locale.US)
 fun isOnboarded()=prefs.getBoolean("onboarded",false);fun setOnboarded(v:Boolean)=prefs.edit().putBoolean("onboarded",v).apply()
 fun settings():AppSettings{val raw=prefs.getString("settings",null)?:return AppSettings();return runCatching{val o=JSONObject(raw);AppSettings(o.optBoolean("darkMode",false),o.optBoolean("haptics",true),o.optBoolean("sounds",false),o.optBoolean("reducedMotion",false),o.optBoolean("largeText",false),o.optBoolean("privacyScreenProtection",false),runCatching{CoachLevel.valueOf(o.optString("coachLevel",CoachLevel.FULL.name))}.getOrDefault(CoachLevel.FULL))}.getOrDefault(AppSettings())}
 fun saveSettings(v:AppSettings){val o=JSONObject().put("darkMode",v.darkMode).put("haptics",v.haptics).put("sounds",v.sounds).put("reducedMotion",v.reducedMotion).put("largeText",v.largeText).put("privacyScreenProtection",v.privacyScreenProtection).put("coachLevel",v.coachLevel.name);prefs.edit().putString("settings",o.toString()).apply()}
 fun profile():UserProfile{val raw=prefs.getString("profile",null)?:return UserProfile();return runCatching{val o=JSONObject(raw);UserProfile(o.optInt("targetWpm",50).coerceIn(20,120),o.optInt("targetAccuracy",97).coerceIn(80,100),o.optInt("dailyGoalMinutes",10).coerceIn(5,60),runCatching{TrainingFocus.valueOf(o.optString("focus",TrainingFocus.BALANCED.name))}.getOrDefault(TrainingFocus.BALANCED),o.optInt("baselineWpm",0).coerceAtLeast(0),o.optInt("baselineAccuracy",0).coerceIn(0,100))}.getOrDefault(UserProfile())}
 fun saveProfile(v:UserProfile){val o=JSONObject().put("targetWpm",v.targetWpm).put("targetAccuracy",v.targetAccuracy).put("dailyGoalMinutes",v.dailyGoalMinutes).put("focus",v.focus.name).put("baselineWpm",v.baselineWpm).put("baselineAccuracy",v.baselineAccuracy);prefs.edit().putString("profile",o.toString()).apply()}
 fun xp()=prefs.getInt("xp",0);fun totalCharacters()=prefs.getInt("total_characters",0);fun totalSeconds()=prefs.getLong("total_seconds",0L);fun bestWpm()=prefs.getInt("best_wpm",0);fun streak()=prefs.getInt("streak",0)
 fun completedLessonIds():Set<Int>=(prefs.getStringSet("completed_lessons",emptySet())?:emptySet()).mapNotNull{it.toIntOrNull()}.toSet();fun completionCount()=completedLessonIds().size
 fun history():List<HistoryEntry>{val raw=prefs.getString("history",null)?:return emptyList();return runCatching{val a=JSONArray(raw);buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(HistoryEntry(o.optLong("epochMs"),o.optInt("wpm"),o.optInt("accuracy"),o.optInt("thumbScore"),o.optInt("minutes"),o.optString("title","Session").take(80)))}}}.getOrDefault(emptyList())}
 fun keyStats():Map<Char,KeyAggregate>{val raw=prefs.getString("key_stats",null)?:return emptyMap();return runCatching{val o=JSONObject(raw);buildMap{o.keys().forEach{k->if(k.isNotEmpty()){val s=o.getJSONObject(k);put(k[0],KeyAggregate(s.optInt("presses"),s.optInt("errors"),s.optLong("totalReactionMs")))}}}}.getOrDefault(emptyMap())}
 fun transitionStats():Map<String,TransitionAggregate>{val raw=prefs.getString("transition_stats",null)?:return emptyMap();return runCatching{val o=JSONObject(raw);buildMap{o.keys().forEach{k->val s=o.getJSONObject(k);put(k.take(4),TransitionAggregate(s.optInt("count"),s.optInt("errors"),s.optLong("totalMs")))}}}.getOrDefault(emptyMap())}
 fun todaySeconds()=prefs.getLong("practice_${dateFormat.format(Date())}",0L);fun currentThumbScore()=history().lastOrNull()?.thumbScore?:0;fun lastWpm()=history().lastOrNull()?.wpm?:profile().baselineWpm;fun lastAccuracy()=history().lastOrNull()?.accuracy?:profile().baselineAccuracy
 fun saveSession(r:SessionResult,l:Lesson){val e=prefs.edit();e.putInt("xp",xp()+l.xp).putInt("total_characters",totalCharacters()+r.chars).putLong("total_seconds",totalSeconds()+r.durationMs/1000).putInt("best_wpm",maxOf(bestWpm(),r.netWpm));if(l.id>0&&!l.isPractice)e.putStringSet("completed_lessons",completedLessonIds().toMutableSet().apply{add(l.id)}.map(Int::toString).toSet());val today=dateFormat.format(Date());e.putLong("practice_$today",todaySeconds()+r.durationMs/1000);updateStreak(e,today);val h=(history()+HistoryEntry(System.currentTimeMillis(),r.netWpm,r.accuracy,r.thumbScore,((r.durationMs/60000.0).coerceAtLeast(.1)).roundToInt(),r.title)).takeLast(60);e.putString("history",historyJson(h).toString());val keys=keyStats().toMutableMap();r.keyUpdates.forEach{(k,u)->val o=keys[k]?:KeyAggregate();keys[k]=KeyAggregate(o.presses+u.presses,o.errors+u.errors,o.totalReactionMs+u.totalReactionMs)};e.putString("key_stats",keyJson(keys).toString());val trans=transitionStats().toMutableMap();r.transitionUpdates.forEach{(k,u)->val o=trans[k]?:TransitionAggregate();trans[k]=TransitionAggregate(o.count+u.count,o.errors+u.errors,o.totalMs+u.totalMs)};e.putString("transition_stats",transitionJson(trans).toString()).apply();if(l.id==0){val p=profile();saveProfile(p.copy(baselineWpm=r.netWpm,baselineAccuracy=r.accuracy));setOnboarded(true)}}
 private fun updateStreak(e:android.content.SharedPreferences.Editor,today:String){val last=prefs.getString("last_practice_date",null);if(last==today)return;val y=Calendar.getInstance().apply{add(Calendar.DAY_OF_YEAR,-1)};val next=if(last==dateFormat.format(y.time))streak()+1 else 1;e.putInt("streak",next).putString("last_practice_date",today)}
 fun topWeakKeys(limit:Int=6)=keyStats().entries.filter{it.key.isLetterOrDigit()&&it.value.presses+it.value.errors>=2}.sortedByDescending{it.value.errors*650+it.value.averageReactionMs}.take(limit).map{it.key to it.value}
 fun topWeakTransitions(limit:Int=6)=transitionStats().entries.filter{it.value.count+it.value.errors>=2}.sortedByDescending{it.value.errors*700+it.value.averageMs}.take(limit).map{it.key to it.value}
 fun dailyWorkout():List<DailyWorkoutItem>{val weak=TrainingEngine.generateWeakDrill(keyStats(),transitionStats());return listOf(DailyWorkoutItem("Warm-up","Easy alternating words",2,Lesson(-20,0,"Warm-up","Find a smooth pace","we type better with calm steady rhythm today","Warm-up",20,isPractice=true)),DailyWorkoutItem("Weakness trainer","Built from your recorded weak keys",3,Lesson(-21,0,"Weakness Trainer","Personalized from your data",weak,"Weakness",30,isPractice=true)),DailyWorkoutItem("Rhythm","Make key timing more even",2,Lesson(-22,0,"Rhythm Trainer","Smooth left-right transitions","read your great new idea then bring the bright thing home","Rhythm",25,isPractice=true)),DailyWorkoutItem("Speed finish","Controlled pace, not reckless speed",3,Lesson(-23,0,"Speed Finish","Finish your daily workout","mobile typing becomes fast when accuracy rhythm and reach work together","Speed",35,60,true)))}
 fun achievements():List<Pair<String,Boolean>>{val h=history();val a=h.maxOfOrNull{it.accuracy}?:0;val s=h.maxOfOrNull{it.thumbScore}?:0;return listOf("First session" to h.isNotEmpty(),"30 WPM" to(bestWpm()>=30),"40 WPM" to(bestWpm()>=40),"50 WPM Club" to(bestWpm()>=50),"98% Accuracy" to(a>=98),"Perfect Accuracy" to(a==100),"7 Day Streak" to(streak()>=7),"10K Characters" to(totalCharacters()>=10000),"ThumbScore 800" to(s>=800),"Curriculum 50%" to(completionCount()>=LessonRepository.lessons.size/2))}
 fun exportJson():String=JSONObject().put("format","ThumbTypeBackup").put("version",3).put("createdAt",System.currentTimeMillis()).put("profile",JSONObject(prefs.getString("profile","{}")?:"{}")).put("settings",JSONObject(prefs.getString("settings","{}")?:"{}")).put("xp",xp()).put("totalCharacters",totalCharacters()).put("totalSeconds",totalSeconds()).put("bestWpm",bestWpm()).put("streak",streak()).put("completedLessons",JSONArray(completedLessonIds().sorted())).put("history",historyJson(history())).put("keyStats",keyJson(keyStats())).put("transitionStats",transitionJson(transitionStats())).toString(2)
 fun importJson(raw:String):Result<Unit>=runCatching{require(raw.length<=2000000);val root=JSONObject(raw);require(root.optString("format")=="ThumbTypeBackup");require(root.optInt("version") in 1..3);val h=root.optJSONArray("history")?:JSONArray();require(h.length()<=1000);val c=root.optJSONArray("completedLessons")?:JSONArray();val set=buildSet{for(i in 0 until minOf(c.length(),200)){val v=c.optInt(i,-1);if(v>=0)add(v.toString())}};prefs.edit().putBoolean("onboarded",true).putString("profile",(root.optJSONObject("profile")?:JSONObject()).toString()).putString("settings",(root.optJSONObject("settings")?:JSONObject()).toString()).putInt("xp",root.optInt("xp").coerceIn(0,10000000)).putInt("total_characters",root.optInt("totalCharacters").coerceAtLeast(0)).putLong("total_seconds",root.optLong("totalSeconds").coerceIn(0,100000000)).putInt("best_wpm",root.optInt("bestWpm").coerceIn(0,300)).putInt("streak",root.optInt("streak").coerceIn(0,10000)).putStringSet("completed_lessons",set).putString("history",h.toString()).putString("key_stats",(root.optJSONObject("keyStats")?:JSONObject()).toString()).putString("transition_stats",(root.optJSONObject("transitionStats")?:JSONObject()).toString()).apply()}
 fun clearAll()=prefs.edit().clear().apply()
 private fun historyJson(items:List<HistoryEntry>)=JSONArray().apply{items.forEach{h->put(JSONObject().put("epochMs",h.epochMs).put("wpm",h.wpm).put("accuracy",h.accuracy).put("thumbScore",h.thumbScore).put("minutes",h.minutes).put("title",h.title))}}
 private fun keyJson(items:Map<Char,KeyAggregate>)=JSONObject().apply{items.forEach{(k,s)->put(k.toString(),JSONObject().put("presses",s.presses).put("errors",s.errors).put("totalReactionMs",s.totalReactionMs))}}
 private fun transitionJson(items:Map<String,TransitionAggregate>)=JSONObject().apply{items.forEach{(k,s)->put(k,JSONObject().put("count",s.count).put("errors",s.errors).put("totalMs",s.totalMs))}}
}
