package com.sadam.thumbtype.mobile

object LessonRepository {
    val stageNames=mapOf(1 to "Foundation",2 to "Reach Control",3 to "Rhythm",4 to "Real-World Typing",5 to "Precision & Symbols",6 to "Advanced Speed")
    val lessons=listOf(
        Lesson(1,1,"Two-Thumb Setup","Understand mobile reach zones","we type with two thumbs and keep movement small","Technique"),Lesson(2,1,"Left Zone I","Q W E R and A S D F","we read safe words fast","Left reach"),Lesson(3,1,"Right Zone I","U I O P and J K L M","you look up online","Right reach"),Lesson(4,1,"Bottom Reach","Z X C V and M","move calm words with care","Bottom row"),Lesson(5,1,"Space Rhythm","Alternate naturally around space","we type better when space feels easy","Space"),Lesson(6,1,"Foundation Check","Combine your basic zones","your mobile typing can feel smooth and light","Technique",60),
        Lesson(7,2,"Top Row Reach","Control long top-row movement","write your quiet report today","Top row"),Lesson(8,2,"Middle Row Reach","Keep thumbs close to home zones","a good skill feels steady","Middle row"),Lesson(9,2,"Bottom Row Reach","Build confidence without overreaching","zoom back and move calmly","Bottom row"),Lesson(10,2,"Center T / Y","Use adaptive center reach","try to type your tiny story","Center keys"),Lesson(11,2,"Center G / H","Choose the shorter transition","going home brings good rhythm","Center keys"),Lesson(12,2,"Center B / N","Train lower-center movement","bring another bright number","Center keys",60),
        Lesson(13,3,"Alternation I","Develop left-right flow","read your great new idea","Rhythm"),Lesson(14,3,"Alternation II","Longer alternating sequences","better typing grows with natural movement","Rhythm"),Lesson(15,3,"Same-Side Control","Stay relaxed through repeated-side keys","safe areas are still useful","Control"),Lesson(16,3,"Transition Timing","Reduce pauses between letters","think then bring the right thing","Timing"),Lesson(17,3,"Word Rhythm","Keep a consistent pace across words","steady words create reliable speed","Rhythm"),Lesson(18,3,"Rhythm Check","Balance speed and even timing","smooth rhythm makes mobile typing easier","Rhythm",60),
        Lesson(19,4,"Everyday Chat","Common mobile conversation","Hey, I am almost there. Please send the location.","Chat"),Lesson(20,4,"Questions","Fast natural questions","Where are you? Can you call me when you arrive?","Chat"),Lesson(21,4,"Work Message","Professional short replies","Hello, I reviewed the update. Everything looks good.","Work"),Lesson(22,4,"Email Flow","Professional sentence structure","Hi team, the file is ready. Please review it today.","Email"),Lesson(23,4,"Search & URLs","Domains and common web patterns","open thumbtype.app then search mobile typing practice","Web"),Lesson(24,4,"Real-World Check","Mix chat, work and search","Thanks, I checked the file. I will send the final link shortly.","Real world",70),
        Lesson(25,5,"Capital Letters","Practice mobile shift behavior","Today I Will Practice Better Mobile Typing","Capitals"),Lesson(26,5,"Basic Punctuation","Commas, periods and questions","Wait, are you sure? Yes, I checked it.","Punctuation"),Lesson(27,5,"Numbers","Prices and quantities","Order 48291 costs 7450 PKR","Numbers"),Lesson(28,5,"Dates & Times","Common numeric transitions","Meet at 10:30 on 28/08/2026","Numbers"),Lesson(29,5,"Email Symbols","At signs, dots and domains","email hello@thumbtype.app for support","Symbols"),Lesson(30,5,"Precision Check","Accuracy under mixed input","At 9:45, send 2 files to team@example.com.","Precision",70),
        Lesson(31,6,"40 WPM Builder","Controlled acceleration","fast mobile typing comes from accuracy rhythm and efficient reach","Speed",80),Lesson(32,6,"Consistency","Hold one pace for longer","keep the same calm tempo from the first word to the final word","Consistency",80),Lesson(33,6,"Weak Transition Lab","Harder center combinations","bring the bright thing tonight then begin another thought","Transitions",80),Lesson(34,6,"Endurance","Longer professional passage","A reliable mobile typist stays relaxed, reads ahead, keeps both thumbs moving efficiently, and protects accuracy while speed increases.","Endurance",90),Lesson(35,6,"60-Second Challenge","Measure your controlled speed","typing faster does not mean rushing every key it means reducing hesitation while keeping mistakes under control","Speed",100,60),Lesson(36,6,"Elite Assessment","Full technique assessment","Great mobile typing combines accurate keys, balanced reach, smooth rhythm, quick transitions, and consistent attention from start to finish.","Assessment",150,90)
    )
    val practiceModes=listOf(
        PracticeMode("15s Sprint","Short burst for reaction speed","smooth quick mobile typing with calm accurate movement",15,"Speed"),PracticeMode("30s Speed","Controlled pace test","mobile typing gets faster when you trust rhythm and keep your thumbs relaxed",30,"Speed"),PracticeMode("60s Benchmark","Standard personal record test","reliable speed comes from accurate movement steady timing and confidence across every row of the mobile keyboard",60,"Benchmark"),PracticeMode("2m Endurance","Hold quality for longer","A strong mobile typist does not chase every character. The goal is to maintain an efficient rhythm, read ahead, recover calmly from mistakes, and keep accuracy stable for the whole session.",120,"Endurance"),PracticeMode("Accuracy Lab","Precision before speed","accuracy first type every character carefully and avoid unnecessary corrections",skill="Accuracy"),PracticeMode("Rhythm Trainer","Even transitions","read your great new idea then bring the bright thing home",skill="Rhythm"),PracticeMode("Weakness Trainer","Auto-generated from your history","",skill="Weakness"),PracticeMode("Chat","Everyday messaging","Hey, I am almost there. Can you send your exact location? Thanks!",skill="Chat"),PracticeMode("Work","Professional mobile writing","Hello, I reviewed the latest changes. Two small issues remain before publishing.",skill="Work"),PracticeMode("Numbers","Dates, times and prices","Order 48291 costs 7450 PKR. Delivery is on 30/08/2026 at 2:30 PM.",skill="Numbers"),PracticeMode("URLs","Domains and email","open thumbtype.app/start then email hello@thumbtype.app",skill="Web"),PracticeMode("Punctuation","Common mobile symbols","Wait, are you sure? Yes, I checked it. Great!",skill="Punctuation"))
    fun nextLesson(completed:Set<Int>)=lessons.firstOrNull{it.id !in completed}?:lessons.last()
    fun dailyChallenge(daySeed:Int):Lesson{val o=listOf("today we train smooth two thumb rhythm with careful center key transitions","a short daily challenge keeps speed accuracy and confidence moving forward","practice the difficult keys calmly then finish with one clean fast sentence","mobile speed grows when each thumb travels less and the typing rhythm stays even");return Lesson(-90,0,"Daily Challenge","One focused challenge for today",o[kotlin.math.abs(daySeed)%o.size],"Daily",60,60,true)}
}
