package com.sadam.thumbtype.mobile
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp
val ThumbIndigo=Color(0xFF5865F2);val ThumbIndigoDark=Color(0xFF8E98FF);val ThumbMint=Color(0xFF2DD4A8);val ThumbAmber=Color(0xFFFFB84D);val Ink=Color(0xFF151B2B);val Night=Color(0xFF090E1A)
private val Light=lightColorScheme(primary=ThumbIndigo,onPrimary=Color.White,primaryContainer=Color(0xFFE9EBFF),onPrimaryContainer=Color(0xFF1D276F),secondary=Color(0xFF078B70),onSecondary=Color.White,secondaryContainer=Color(0xFFD8F8EE),onSecondaryContainer=Color(0xFF064D3F),tertiary=Color(0xFF9C6400),tertiaryContainer=Color(0xFFFFE6B8),background=Color(0xFFF7F8FC),surface=Color.White,surfaceVariant=Color(0xFFF0F2F7),onSurface=Ink,onSurfaceVariant=Color(0xFF667085),outline=Color(0xFFD5D9E3),outlineVariant=Color(0xFFE7E9EF),error=Color(0xFFCB3452),errorContainer=Color(0xFFFFE7EC))
private val Dark=darkColorScheme(primary=ThumbIndigoDark,onPrimary=Color(0xFF11184A),primaryContainer=Color(0xFF29317A),onPrimaryContainer=Color(0xFFE8E9FF),secondary=Color(0xFF6EE7C7),onSecondary=Color(0xFF05392F),secondaryContainer=Color(0xFF0D4F42),onSecondaryContainer=Color(0xFFD6FFF2),tertiary=Color(0xFFFFC970),tertiaryContainer=Color(0xFF5A3B00),background=Night,surface=Color(0xFF111827),surfaceVariant=Color(0xFF192234),onSurface=Color(0xFFF5F7FC),onSurfaceVariant=Color(0xFFAAB3C4),outline=Color(0xFF3C465A),outlineVariant=Color(0xFF273246),error=Color(0xFFFF8EA3),errorContainer=Color(0xFF5F2130))
private fun typography(scale:Float)=Typography(headlineLarge=TextStyle(FontFamily.SansSerif,FontWeight.Black,(32*scale).sp,lineHeight=(37*scale).sp),headlineMedium=TextStyle(FontFamily.SansSerif,FontWeight.ExtraBold,(26*scale).sp,lineHeight=(31*scale).sp),titleLarge=TextStyle(FontFamily.SansSerif,FontWeight.Bold,(21*scale).sp,lineHeight=(27*scale).sp),titleMedium=TextStyle(FontFamily.SansSerif,FontWeight.Bold,(17*scale).sp,lineHeight=(23*scale).sp),bodyLarge=TextStyle(FontFamily.SansSerif,FontWeight.Normal,(16*scale).sp,lineHeight=(24*scale).sp),bodyMedium=TextStyle(FontFamily.SansSerif,FontWeight.Normal,(14*scale).sp,lineHeight=(21*scale).sp),labelLarge=TextStyle(FontFamily.SansSerif,FontWeight.Bold,(14*scale).sp),labelMedium=TextStyle(FontFamily.SansSerif,FontWeight.SemiBold,(12*scale).sp))
@Composable fun ThumbTypeTheme(settings:AppSettings,content:@Composable()->Unit){MaterialTheme(colorScheme=if(settings.darkMode)Dark else Light,typography=typography(if(settings.largeText)1.1f else 1f),content=content)}
