package com.sadam.thumbtype.mobile

import android.media.AudioManager
import android.media.ToneGenerator
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.hapticfeedback.HapticFeedbackType
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.layout.onGloballyPositioned
import androidx.compose.ui.layout.positionInWindow
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.platform.LocalHapticFeedback
import androidx.compose.ui.text.SpanStyle
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.withStyle
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.delay
import kotlin.math.roundToInt

@Composable
fun TrainerScreen(lesson:Lesson,settings:AppSettings,profile:UserProfile,onExit:()->Unit,onComplete:(SessionResult)->Unit){
 val target=remember(lesson.id){val t=lesson.text.trim().ifBlank{"type with calm accurate two thumb rhythm"};if(lesson.timeLimitSeconds!=null)List(5){t}.joinToString(" ") else t}
 var index by remember{mutableIntStateOf(0)};val events=remember{mutableStateListOf<PressEvent>()};var started by remember{mutableLongStateOf(0L)};var lastAt by remember{mutableLongStateOf(0L)};var previousRecommendation by remember{mutableStateOf<ThumbSide?>(null)};var layer by remember{mutableStateOf(KeyboardLayer.LETTERS)};var shift by remember{mutableStateOf(false)};var wrong by remember{mutableStateOf(false)};var finished by remember{mutableStateOf(false)};var now by remember{mutableLongStateOf(System.currentTimeMillis())};val haptic=LocalHapticFeedback.current;val tone=remember{ToneGenerator(AudioManager.STREAM_MUSIC,25)};DisposableEffect(Unit){onDispose{tone.release()}}
 val expected=target.getOrNull(index);val recommendation=expected?.let{TrainingEngine.recommendedThumb(it,target.getOrNull(index-1),target.getOrNull(index+1),previousRecommendation)}?:ThumbSide.FLEX
 fun finish(duration:Long?=null){if(finished)return;finished=true;val d=duration?:if(started==0L)1L else System.currentTimeMillis()-started;onComplete(TrainingEngine.calculateResult(lesson.title,events.toList(),d,profile.targetWpm))}
 LaunchedEffect(started,finished){while(started>0&&!finished){now=System.currentTimeMillis();val limit=lesson.timeLimitSeconds;if(limit!=null&&now-started>=limit*1000L){finish(limit*1000L);break};delay(150)}}
 val elapsed=if(started==0L)0L else(now-started).coerceAtLeast(1);val wpm=if(elapsed<800)0 else(((index/5.0)/(elapsed/60000.0))).roundToInt().coerceAtMost(250);val acc=if(events.isEmpty())100 else(events.count{it.correct}*100.0/events.size).roundToInt();val rhythm=TrainingEngine.rhythmScore(events.filter{it.correct}.drop(1).map{it.elapsedFromPreviousMs});val progress=if(lesson.timeLimitSeconds!=null&&started>0)(elapsed/(lesson.timeLimitSeconds*1000f)).coerceIn(0f,1f)else index/target.length.toFloat().coerceAtLeast(1f);val remaining=lesson.timeLimitSeconds?.let{(it-elapsed/1000L).coerceAtLeast(0)}
 Column(Modifier.fillMaxSize()){
  Row(Modifier.fillMaxWidth().padding(horizontal=8.dp,vertical=6.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=onExit){Icon(Icons.Default.Close,"Exit")};Column(Modifier.weight(1f)){Text(lesson.title,fontWeight=FontWeight.Bold,maxLines=1);Text(lesson.skill,fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)};TinyPill(remaining?.let{"${it}s"}?:"${(progress*100).toInt()}%",if(remaining!=null)Icons.Default.Timer else Icons.Default.Timeline)};LinearProgressIndicator(progress={progress},Modifier.fillMaxWidth().height(5.dp),trackColor=MaterialTheme.colorScheme.surfaceVariant)
  Column(Modifier.weight(1f).padding(16.dp),verticalArrangement=Arrangement.spacedBy(11.dp)){Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){LiveMetric("$wpm","WPM",Modifier.weight(1f));LiveMetric("$acc%","Accuracy",Modifier.weight(1f));LiveMetric("$rhythm%","Rhythm",Modifier.weight(1f));LiveMetric("${events.count{!it.correct}}","Errors",Modifier.weight(1f))};PremiumCard{Text("TARGET",fontSize=10.sp,fontWeight=FontWeight.Black,color=MaterialTheme.colorScheme.primary);Spacer(Modifier.height(7.dp));TargetText(target,index,wrong,settings.largeText)};if(settings.coachLevel!=CoachLevel.OFF&&expected!=null)ThumbCoach(expected,recommendation,layer,shift,settings.coachLevel==CoachLevel.MINIMAL)}
  TrainingKeyboard(expected,recommendation,layer,shift,settings,onLayer={layer=if(layer==KeyboardLayer.LETTERS)KeyboardLayer.NUMBERS else KeyboardLayer.LETTERS;wrong=false},onShift={shift=!shift;wrong=false}){raw,touchSide->if(!finished&&expected!=null){val time=System.currentTimeMillis();if(started==0L){started=time;lastAt=time;now=time};val entered=if(raw.isLetter()&&shift)raw.uppercaseChar()else raw.lowercaseChar();val ok=entered==expected;events+=PressEvent(expected,entered,ok,(time-lastAt).coerceAtLeast(1),recommendation,touchSide);lastAt=time;if(ok){if(settings.sounds)tone.startTone(ToneGenerator.TONE_PROP_BEEP,15);wrong=false;previousRecommendation=recommendation;index++;shift=false;if(index>=target.length)finish()}else{if(settings.haptics)haptic.performHapticFeedback(HapticFeedbackType.LongPress);if(settings.sounds)tone.startTone(ToneGenerator.TONE_PROP_NACK,45);wrong=true}}}
 }
}

@Composable private fun LiveMetric(value:String,label:String,modifier:Modifier){Surface(modifier,shape=RoundedCornerShape(14.dp),color=MaterialTheme.colorScheme.surface){Column(Modifier.padding(vertical=8.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(value,fontWeight=FontWeight.Black,fontSize=16.sp);Text(label,fontSize=8.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable private fun TargetText(text:String,index:Int,wrong:Boolean,large:Boolean){val p=MaterialTheme.colorScheme.primary;val s=MaterialTheme.colorScheme.secondary;val e=MaterialTheme.colorScheme.error;val m=MaterialTheme.colorScheme.onSurfaceVariant;val a=buildAnnotatedString{text.forEachIndexed{i,c->when{ i<index->withStyle(SpanStyle(color=s,fontWeight=FontWeight.SemiBold)){append(c)};i==index->withStyle(SpanStyle(color=if(wrong)e else p,background=(if(wrong)e else p).copy(.14f),fontWeight=FontWeight.Black)){append(c)};else->withStyle(SpanStyle(color=m)){append(c)}}}};Text(a,fontSize=if(large)23.sp else 20.sp,lineHeight=if(large)34.sp else 30.sp,fontWeight=FontWeight.Medium)}
@Composable private fun ThumbCoach(expected:Char,side:ThumbSide,layer:KeyboardLayer,shift:Boolean,minimal:Boolean){val needLayer=TrainingEngine.requiredLayer(expected)!=layer;val needShift=expected.isUpperCase()&&!shift;val instruction=when{needLayer->if(TrainingEngine.requiredLayer(expected)==KeyboardLayer.NUMBERS)"Switch to 123" else "Switch to ABC";needShift->"Tap SHIFT first";side==ThumbSide.LEFT->"Left reach → ${expected.uppercase()}";side==ThumbSide.RIGHT->"Right reach → ${expected.uppercase()}";else->"Flexible reach → ${if(expected==' ')"SPACE" else expected.uppercase()}"};Surface(shape=RoundedCornerShape(20.dp),color=MaterialTheme.colorScheme.surface){if(minimal)Box(Modifier.fillMaxWidth().padding(12.dp),contentAlignment=Alignment.Center){Text(instruction,fontWeight=FontWeight.Bold,color=MaterialTheme.colorScheme.primary)}else Column(Modifier.padding(13.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(instruction,fontWeight=FontWeight.Black,color=if(needLayer||needShift)ThumbAmber else MaterialTheme.colorScheme.primary);Spacer(Modifier.height(9.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceEvenly,verticalAlignment=Alignment.CenterVertically){CoachHand("LEFT",side==ThumbSide.LEFT||side==ThumbSide.FLEX,MaterialTheme.colorScheme.primary);Surface(shape=RoundedCornerShape(13.dp),color=if(side==ThumbSide.FLEX)ThumbAmber.copy(.14f)else MaterialTheme.colorScheme.surfaceVariant){Text(if(expected==' ')"SPACE" else expected.uppercase(),Modifier.padding(horizontal=14.dp,vertical=9.dp),fontWeight=FontWeight.Black)};CoachHand("RIGHT",side==ThumbSide.RIGHT||side==ThumbSide.FLEX,MaterialTheme.colorScheme.secondary)}}}}
@Composable private fun CoachHand(label:String,active:Boolean,accent:Color){Column(horizontalAlignment=Alignment.CenterHorizontally){Surface(shape=CircleShape,color=if(active)accent.copy(.15f)else MaterialTheme.colorScheme.surfaceVariant){Icon(Icons.Default.TouchApp,null,Modifier.padding(10.dp).size(23.dp),tint=if(active)accent else MaterialTheme.colorScheme.onSurfaceVariant)};Text(label,fontSize=8.sp,fontWeight=FontWeight.Black,color=if(active)accent else MaterialTheme.colorScheme.onSurfaceVariant)}}

@Composable private fun TrainingKeyboard(expected:Char?,recommended:ThumbSide,layer:KeyboardLayer,shift:Boolean,settings:AppSettings,onLayer:()->Unit,onShift:()->Unit,onKey:(Char,ThumbSide)->Unit){Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(topStart=25.dp,topEnd=25.dp),color=MaterialTheme.colorScheme.surface,tonalElevation=3.dp){Column(Modifier.padding(horizontal=6.dp,vertical=9.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){if(layer==KeyboardLayer.LETTERS){KeyRow("qwertyuiop",expected,recommended,shift,settings,onKey);KeyRow("asdfghjkl",expected,recommended,shift,settings,onKey,12);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(4.dp)){SpecialKey("⇧",shift||expected?.isUpperCase()==true,Modifier.weight(1.15f),onShift);"zxcvbnm".forEach{Key(it,expected,recommended,shift,settings,Modifier.weight(1f),onKey)};SpecialKey("⌫",false,Modifier.weight(1.15f),{})};BottomRow(expected,recommended,settings,onLayer,onKey,"123")}else{KeyRow("1234567890",expected,recommended,false,settings,onKey);KeyRow("@#%&*-+=",expected,recommended,false,settings,onKey,18);KeyRow("()/:;!?",expected,recommended,false,settings,onKey,24);BottomRow(expected,recommended,settings,onLayer,onKey,"ABC")};Text("Reach-match measures the side of the screen tapped; center keys stay adaptive.",Modifier.fillMaxWidth(),fontSize=8.sp,textAlign=TextAlign.Center,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable private fun BottomRow(expected:Char?,recommended:ThumbSide,settings:AppSettings,onLayer:()->Unit,onKey:(Char,ThumbSide)->Unit,label:String){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(4.dp)){SpecialKey(label,true,Modifier.weight(1.35f),onLayer);Key(',',expected,recommended,false,settings,Modifier.weight(.8f),onKey);Key(' ',expected,recommended,false,settings,Modifier.weight(4.2f),onKey,"space");Key('.',expected,recommended,false,settings,Modifier.weight(.8f),onKey);Key('?',expected,recommended,false,settings,Modifier.weight(1f),onKey)}}
@Composable private fun KeyRow(chars:String,expected:Char?,recommended:ThumbSide,shift:Boolean,settings:AppSettings,onKey:(Char,ThumbSide)->Unit,pad:Int=0){Row(Modifier.fillMaxWidth().padding(horizontal=pad.dp),horizontalArrangement=Arrangement.spacedBy(4.dp)){chars.forEach{Key(it,expected,recommended,shift,settings,Modifier.weight(1f),onKey)}}}
@Composable private fun Key(char:Char,expected:Char?,recommended:ThumbSide,shift:Boolean,settings:AppSettings,modifier:Modifier,onKey:(Char,ThumbSide)->Unit,label:String?=null){val cfg=LocalConfiguration.current;val density=LocalDensity.current;val widthPx=with(density){cfg.screenWidthDp.dp.toPx()};var x by remember(char){mutableFloatStateOf(0f)};val active=expected?.let{if(char==' ')it==' ' else it.lowercaseChar()==char.lowercaseChar()}==true;val zone=TrainingEngine.fixedZone(char);val bg=when{active->MaterialTheme.colorScheme.primary;zone==ThumbSide.LEFT->MaterialTheme.colorScheme.primary.copy(.075f);zone==ThumbSide.RIGHT->MaterialTheme.colorScheme.secondary.copy(.09f);else->ThumbAmber.copy(.08f)};Surface(modifier.height(44.dp).onGloballyPositioned{x=it.positionInWindow().x}.pointerInput(char,widthPx,shift){detectTapGestures{local->onKey(char,if(x+local.x<widthPx/2)ThumbSide.LEFT else ThumbSide.RIGHT)}},shape=RoundedCornerShape(11.dp),color=bg){Box(contentAlignment=Alignment.Center){Text(label?:if(char.isLetter()&&shift)char.uppercase()else char.toString(),fontWeight=FontWeight.Bold,color=if(active)MaterialTheme.colorScheme.onPrimary else MaterialTheme.colorScheme.onSurface,fontSize=if(label!=null)11.sp else 15.sp);if(active&&recommended!=ThumbSide.FLEX&&settings.coachLevel==CoachLevel.FULL)Box(Modifier.align(if(recommended==ThumbSide.LEFT)Alignment.BottomStart else Alignment.BottomEnd).padding(4.dp).size(5.dp).background(MaterialTheme.colorScheme.onPrimary,CircleShape))}}}
@Composable private fun SpecialKey(label:String,active:Boolean,modifier:Modifier,onClick:()->Unit){Surface(modifier.height(44.dp).pointerInput(label){detectTapGestures{onClick()}},shape=RoundedCornerShape(11.dp),color=if(active)ThumbAmber.copy(.18f)else MaterialTheme.colorScheme.surfaceVariant){Box(contentAlignment=Alignment.Center){Text(label,fontSize=11.sp,fontWeight=FontWeight.Black,color=if(active)ThumbAmber else MaterialTheme.colorScheme.onSurfaceVariant)}}}
